server:
  port: 8080
  servlet:
    context-path: /login

#数据库及redis配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://112.124.15.176:3306/study_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong&useSSL=false
  application:
    name: login-in-system
  redis:
    database: 0
    host: 112.124.15.176
    port: 6379
    timeout: 10000
    #邮箱配置
  mail:
    host: smtp.163.com
    username: lsy_starry@163.com
    password: IKBVFYKHMLFKPNQM
    protocol: smtp
    port: 465
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              fallback: false
              class: com.fintech.modules.base.util.mail.MailSSLSocketFactory
    default-encoding: UTF-8

#eureka配置
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/server/eureka
  instance:
    instance-id: login-system-8080
    prefer-ip-address: true


#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lsy.demo.repo.model
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0
  config-location: classpath:mybatis-config.xml
