server:
  port: 8010

spring:
  application:
    name: image-video-process

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/server/eureka
  instance:
    instance-id: image-video-8010
    prefer-ip-address: true

